program          = {statement | expr | begin_block};
statement        = select_statement | func_def;
select_statement = "SELECT" cols "FROM" db ["WHERE" bool_expr];
cols             = "*" | const {"," const};
db               = ID;
func_def         = "DEFUN" ID ":" [ID {"," ID}] "->" program;
expr             = const | asgn | begin_block;
bool_expr        = const ("=" | "<>") const | bool_fact {("|" | "&") bool_fact};
bool_fact        = const | "!" bool_fact | "(" expr ")";
str_expr         = str_fact {"||" str_fact};
str_fact         = const | "(" expr ")";
asgn             = "SET" ID ":=" const;
const            = bool_expr | str_expr | func_call | ID;
func_call        = ID "(" [const {"," const}] ")";
begin_block      = "BEGIN" [program ";" {program ";"}] "END";
